### PR TITLE
amazonka: fixing sigv4 path encoding so that it happens once for s3 and twice for other services

### LINKED ISSUE #529: SignV4 Canonical URI paths are only encoded once. Should be twice
Per [AWS SignV4 docs](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html)

> Normalize URI paths according to RFC 3986. Remove redundant and relative path components. Each path segment must be URI-encoded twice (except for Amazon S3 which only gets URI-encoded once). 

Most URIs have nothing to encode, which is why it usually works. However, when there is, the signature will be invalid.

As an example from [API Gateway @connections](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html)
The Endpoint is
```
https://{prefix}.execute-api.us-east-1.amazonaws.com/{stage}/@connections/{connection_id}
https://aabbccddee.execute-api.us-east-1.amazonaws.com/production/@connections/R0oXAdfD0kwCH6w=
```
The URI needs to be encode once for the request
```
https://aabbccddee.execute-api.us-east-1.amazonaws.com/prod/%40connections/R0oXAdfD0kwCH6w%3D
```
And then again for the Canonical URI
```
https://aabbccddee.execute-api.us-east-1.amazonaws.com/prod/%2540connections/R0oXAdfD0kwCH6w%253D
```

### PR DESCRIPTION
**Pull request by mwu**
Should fix #529.

I did some manual smoke testing:
* EC2 describe instances calls
* lambda invokeFunction using all name forms (arn, partial arn, partial arn + alias, function name, name + alias)
* S3 getObject on keys including and excluding uri reserved chars

### CODE REVIEW

File: lib/amazonka-core/src/Amazonka/Data/Path.hs [hunk 1]
```diff
@@ -74,6 +79,13 @@ escapePath :: Path a -> EscapedPath
 escapePath (Raw xs) = Encoded (map (URI.urlEncode True) xs)
 escapePath (Encoded xs) = Encoded xs
 
+-- | Escape a path twice for rare occasions like computing the sigv4 canonical path.
```
Comment (endgame) [inline lib/amazonka-core/src/Amazonka/Data/Path.hs:82]:
```suggestion
-- | Escape a path twice. Used when computing the SigV4 canonical path.
```
Reason: it's nearly every AWS request, so better not to call it rare.

File: lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+        aReq
+          & requestPath .~ aPath
+          & requestService .~ svc
+          & requestBody .~ Hashed aBody
+
+  (meta, _) <- base (Tag (sha256Base16 aBody)) req <$> arbitrary <*> arbitrary <*> arbitrary
+  pure (aPath, metaPath meta, metaCanonicalPath meta)
+
+mkNormalizedPath :: Gen RawPath
+mkNormalizedPath = suchThat arbitrary noDots
```
Comment (endgame) [inline lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs:111]:
```suggestion
mkNormalizedPath = arbitrary `suchThat` noDots
```

File: lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+  (_, reqPath, canonicalPath) <- generate $ mkV4Paths (/= "S3") (pure key)
+  toBS reqPath @?= "/bar/baz"
+  untag canonicalPath @?= untag reqPath
+
+mkV4Paths :: (Abbrev -> Bool) -> Gen RawPath -> Gen (RawPath, Base.Path, CanonicalPath)
+mkV4Paths p genPath = do
+  aReq <- arbitrary :: Gen (Request ())
+  aPath <- genPath
+  aService <- arbitrary
+  anAbbrev <- suchThat arbitrary p
```
Comment (endgame) [inline lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs:93]: Can you modify this function to take a `Gen Abbrev`? Otherwise you risk blowing out test suite runtime by re-rolling the abbrev until it returns `S3`.

File: lib/amazonka/CHANGELOG.md [hunk 4]
```diff
@@ -97,6 +97,8 @@ Released: **?**, Compare: [2.0.0-rc1](https://github.com/brendanhay/amazonka/com
 
 ### Fixed
 
+- `amazonka-core`: Fixed sigv4 canonical uri/path encoding issue
```
Comment (endgame) [inline lib/amazonka/CHANGELOG.md:100]:
```suggestion
- `amazonka-core`: Correctly double-url-encode request paths when computing V4 signatures
```

**Review by endgame — CHANGES_REQUESTED** [review]
This is excellent work, thank you - I particularly appreciate the extensive test suite. I have a few small nits to pick but I look forward to merging this soon.

File: lib/amazonka-core/src/Amazonka/Data/Path.hs [hunk 5]
```diff
@@ -59,6 +61,9 @@ type RawPath = Path 'NoEncoding
 
 type EscapedPath = Path 'Percent
 
+newtype TwiceEscapedPath = TwiceEscapedPath (Path 'Percent)
```
Comment (endgame) [inline lib/amazonka-core/src/Amazonka/Data/Path.hs:64]: I think we want to add an additional `TwicePercent` constructor to `data Encoding`, so this can become a type alias for consistency.

Comment (endgame) [reply lib/amazonka-core/src/Amazonka/Data/Path.hs:64]: Wait, nevermind. That doesn't make sense.

File: lib/amazonka-core/src/Amazonka/Data/Path.hs (hunk 1 above)
Comment (endgame) [reply lib/amazonka-core/src/Amazonka/Data/Path.hs:82]: Probably better to put the "Used in SigV4" on the `newtype` declaration so when someone clicks `TwiceEscapedPath` in haddock, they see it.

File: lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs (hunk 3 above)
Comment (mwu) [reply lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs]: Ah, good call.

File: lib/amazonka-core/src/Amazonka/Data/Path.hs (hunk 5 above)
Comment (mwu) [reply lib/amazonka-core/src/Amazonka/Data/Path.hs:65]: I went through the exact same sequence of thoughts, haha.

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs [hunk 6]
```diff
@@ -30,6 +30,7 @@ data V4 = V4
     metaPath :: Path,
```
Comment (endgame) [inline lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:30]: Can we remove this?

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs [hunk 7]
```diff
@@ -125,6 +126,8 @@ type NormalisedHeaders = Tag "normalised-headers" [(ByteString, ByteString)]
 
 type Method = Tag "method" ByteString
 
+type CanonicalPath = Tag "canonical-path" ByteString
+
 type Path = Tag "path" ByteString
```
Comment (endgame) [inline lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:131]: Can we remove this?

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs [hunk 8]
```diff
@@ -261,11 +265,15 @@ canonicalRequest meth path digest query chs shs =
         toBS digest
       ]
 
-escapedPath :: Request a -> Path
-escapedPath r = Tag . toBS . escapePath $
-  case _serviceAbbrev (_requestService r) of
-    "S3" -> _requestPath r
-    _ -> collapsePath (_requestPath r)
+escapedPaths :: Request a -> (Path, CanonicalPath)
```
Comment (endgame) [inline lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:268]: Can we return `CanonicalPath` only, and not a tuple?

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs (hunk 6 above)
Comment (mwu) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:30]: Not really. This one's still used for the actual http request.

Comment (mwu) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:30]: We could remove metaCanonicalPath instead since I only really added it for making testing easier. Tests would have to grab the canonical path from the canonical request after an unlines, which seemed a bit clunky.

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs (hunk 8 above)
Comment (mwu) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:268]: Thinking about this more, yes it's possible. Where the actual http request is constructed, we'd need to do an unescape: https://github.com/brendanhay/amazonka/blob/9043cb4dc894a1a0d0f24375d70df5cb5e3b1ac8/lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs#L160  But it'd have to be typed and not ByteString since it has to know how to go back from twice escaped to only once-escaped as the http request is always made against the once-escaped URL.

Comment (endgame) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:268]: Okay, I didn't realise that the left hand side of the tuple was still used. Would you mind splitting into two functions `escapePath` and `escapeCanonicalPath`?

Comment (mwu) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs]: Yep.

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs (hunk 6 above)
Comment (endgame) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:30]: I feel a bit unsure about it: Is the request assembled in this function the correct type that the test harness could call `canonicalPath` directly?

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs (hunk 7 above)
Comment (endgame) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:131]: Pretty sure the answer is "no".

File: lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs (hunk 6 above)
Comment (mwu) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:30]: How does this look? https://github.com/mwu/amazonka/pull/1

Comment (endgame) [reply lib/amazonka-core/src/Amazonka/Sign/V4/Base.hs:30]: I think it looks good.

**Review by endgame — APPROVED** [review]
All right, so once you get your secondary PR merged I think this is good to go. Would you mind firing off your manual smoke-test requests one last time, too, just to make sure the tweaks are all good?

**Comment by mwu** [comment]
> All right, so once you get your secondary PR merged I think this is good to go. Would you mind firing off your manual smoke-test requests one last time, too, just to make sure the tweaks are all good?

Ok. These all returned success:
* Lambda InvokeFunction with full arn, partial arn, full and partial arn with alias suffix, full and partial arn with alias in qualifier, function name, name with alias suffix, name with alias qualifier.
* S3 GetObject with keys `test/myron/test`, `test//myron//test', `abc:def$1.foo`
* Some other requests with non-empty paths: APIGateway GetStages, Route53 GetHostedZoneLimit
* A few of the examples in the examples project

File: lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs [hunk 9]
```diff
@@ -0,0 +1,115 @@
+-- |
+-- Module      : Test.AWS.Sign.V$
```
Comment (endgame) [inline lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs:2]:
```suggestion
-- Module      : Test.AWS.Sign.V4
```

**Review by endgame — CHANGES_REQUESTED** [review]
Excellent, thank you for being so thorough. One more nit, and one last question: I think I have misunderstood the purpose of the various `metaCanonicalFoo` in the metadata record - it seems like they don't get used anywhere because they get built and immediately passed to `signRequest`. I think you pointed this out earlier? When I asked you to remove it, I didn't realise there was an established practice of keeping this data around. My question is - do you think we should reinstate `metaCanonicalPath`? I think your tests are fine as they are.

File: lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs (hunk 9 above)
Comment (mwu) [reply lib/amazonka-core/test/Test/Amazonka/Sign/V4/Base.hs]: Hah, thanks. I might have fat fingered that.

**Comment by mwu** [comment]
> Excellent, thank you for being so thorough. One more nit, and one last question: I think I have misunderstood the purpose of the various `metaCanonicalFoo` in the metadata record - it seems like they don't get used anywhere because they get built and immediately passed to `signRequest`. I think you pointed this out earlier? When I asked you to remove it, I didn't realise there was an established practice of keeping this data around. My question is - do you think we should reinstate `metaCanonicalPath`? I think your tests are fine as they are.

I think it's fine as it is, too. The canonical path gets logged already as part of the canonical request and I can't see any other use for returning it in the metadata. Carrying it around is only useful for testing but as you said, we should really approach that by expanding the test suite to test the whole signature.

**Review by endgame — APPROVED** [review]
All right then, sounds good. Thanks very much for this.
