### PR TITLE
Conditional ToElement Serialisation for Root XML Elements

### LINKED ISSUE #241: PutObjectACL incorrectly uses `putXML` instead of `put`.
It can not provide a body, if it does you will see something like:

```
[ServiceError] {
  service    = S3
  status     = 400 Bad Request
  code       = UnexpectedContent
  message    = Just This request does not support content
  request-id = Just AEC8FA44647E0C83
}
```

The fix to the generated code needs to be something like: https://github.com/ambiata/mismi/commit/7b3c906814466e59d1b0113df623b664eb6e63ac

This is verified to work as expected, but I don't have me head in the generator enough to be able to quickly make the change, I will have a look but perhaps not quickly.

### PR DESCRIPTION
**Pull request by brendanhay**
This provides a fix for request types such as `PutObjectACL`, which are `PUT` or `POST` requests containing an optional request body. If the field to be serialised in the body results in an empty body, previously an empty root element would be sent resulting in an `UnexpectedContent` error.

This fix ensures the request body will no longer be sent unless the field is actual set via the appropriate lens.

Fixes #241.

### CODE REVIEW

File: amazonka-s3/test/Test/AWS/S3/Internal.hs [hunk 1]
```diff
@@ -13,8 +13,11 @@
 
 module Test.AWS.S3.Internal where
 
+import           Data.Proxy
```
Comment (fmap) [inline amazonka-s3/test/Test/AWS/S3/Internal.hs]: These look redundant.

File: core/src/Network/AWS/Data/XML.hs [hunk 2]
```diff
@@ -4,6 +4,7 @@
 {-# LANGUAGE LambdaCase          #-}
 {-# LANGUAGE OverloadedStrings   #-}
 {-# LANGUAGE ScopedTypeVariables #-}
+{-# LANGUAGE TupleSections       #-}
```
Comment (fmap) [inline core/src/Network/AWS/Data/XML.hs]: Likewise.

File: amazonka-s3/test/Test/AWS/S3/Internal.hs (hunk 1 above)
Comment (brendanhay) [inline amazonka-s3/test/Test/AWS/S3/Internal.hs]: Thanks
